source 'https://rubygems.org'

gem 'rails', '~> 7.0'
gem 'redis', '~> 5.0'
gem 'sidekiq', '~> 7.0'
gem 'sqlite3', '~> 1.4'
gem 'puma', '~> 6.0'

group :development, :test do
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.2'
end