source 'https://rubygems.org'

gem 'falcon', '~> 0.42'
gem 'redis', '~> 5.0'
gem 'json', '~> 2.6'
gem 'rack', '~> 3.0'
gem 'grpc', '~> 1.62'
gem 'grpc-tools', '~> 1.62'

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.1'
end